sudo: required
language: node_js
services:
  - docker
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "stable"
before_script:
  - npm prune
script:
  - npm test
  - npm run docker-test-e2e
after_success:
  - npm run coveralls
branches:
  only:
    - master
    - docker
